#!/usr/bin/env bash
# displays a list of currently running processes

echo "List of currently running processes:"
echo "--------------------------------------"

ps -ef --forest

echo ""
echo "Process hierarchy:"
echo "------------------"

pstree -Ap
