#!/usr/bin/env bash
# creates file, traps some signals, deletes file after receiving SIGQUIT or SIGTERM
sudo bash -c "echo $$ > /var/run/myscript.pid"
i=0
while [ $i -eq 0 ]
do
	echo "To infinity and beyond"
	trap "echo 'Y U no love me?!'" SIGINT
	trap "echo 'I hate the kill command'; sudo bash -c 'rm /var/run/myscript.pid'; exit 15" 15
	trap "sudo bash -c 'rm /var/run/myscript.pid'; exit 3" 3
	sleep 2
done
