#!/usr/bin/env bash
#This Bash script does the following:
#	1. Create a file /var/run/myscript.pid containing the script PID
#	2. Display "To infinity and beyond" indefinitely
#	3. Display "I hate the kill command" upon receiving a SIGTERM
#	4. Display "Y U no love me?"! when it receives SIGINT
# 	5. Deletes the file /var/run/myscript.pid and terminates whenit receives
#a SIGQUIT or SIGTERM.

terminator() {
	rm /var/run/myscript.pid
	exit
}
echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done
