#!/usr/bin/env bash
#A Bash script that displays "To infinity and beyond" indefinitely
#with a sleep in between each iteration.
#Display  "I am invincible!!!" when it receives a SIGTERM signal

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
