#!/usr/bin/env bash
# This bash script writes "I am alive" to the file /tmp/my_process indefinitely.
#  Pause for 2 seconds in between each message

while true
do
	echo "I am alive!" >> /tmp/my_process
	sleep 2
done
