#!/usr/bin/env bash
#This bash script displays numbers from 1 to 100 on these conditions:
#	Display "FizzBuzz" when the number is a multiple of 3 and 5
#	Display "Fizz" when the number is a multiple of 3
#	Display "Buzz" when the number is a multiple of 5
#	Otherwise, display the number in a list format.

n=1
while [ $n -le 100 ]
do
	if (( "$n" % 15 == 0 ))
	then
		echo "FizzBuzz"
	elif (( "$n" % 3 == 0 ))
	then
		echo "Fizz"
	elif (( "$n" % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$n"
	fi
	(( n++ ))
done
