#!/usr/bin/env bash
#This script display "Best School" multiple times up to 10 lines but
#display "bad luck" on line 4 and "good luck" on line 8.

i=0
while (( "$i"<10 ))
do
	if (( "$i"==3 ))
	then
		echo "bad luck"
	elif (( "$i"==7 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i += 1 ))
done
