#!/usr/bin/env bash
#A script that displays numbers from 1 to 20 and display comment for
#count of 4, 9 and 17 as follows:
#	"bad luck from China" for the 4th iteration
#	"bad luck from Japan" for the 9th iteration
#	"bad luck from Italy" for the 17th iteration

i=1
while (( "$i"<=20 ))
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( i++ ))
done
	
