#!/usr/bin/env bash
#A bash script that display the time for 12 hours and 59 minutes as:
#	display hours from 0 to 12
#	display minutes from 1 to 59

hour=0
while (( hour <= 12 ))
do
	echo "Hour: $hour"
	minute=1
	while (( minute <= 59 ))
	do
		echo "$minute"
		(( minute++ ))
	done
	(( hour++ ))
done
