#!/usr/bin/env bash
#A bash script that displays:
#	The content of the current directory
#	In a list format
#	Display only the part of the name after the first dash

list=$(ls)
for i in $list;
do
	echo "$i" | cut -d '-' -f2
done
