#!/usr/bin/env bash
#This Bash script configures:
#	localhost on Ubuntu server resolves to 127.0.0.2
#	facebook.com on Ubuntu server resolves to 8.8.8.8

cp /etc/hosts ~/host.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.alternate
cp -f ~/hosts.new /etc/hosts
