#!/usr/bin/env bash
#This Bash script configures:
#	localhost on Ubuntu server resolves to 127.0.0.2
#	facebook.com on Ubuntu server resolves to 8.8.8.8

cp /etc/hosts ~/hosts.alternate
sed -i "s/127.0.0.1/127.0.0.2/g" ~/hosts.alternate
echo "8.8.8.8		facebook.com" >> ~/hosts.alternate
cp -f ~/hosts.alternate /etc/hosts
