#!/bin/bash

# Set the parameters
KEY_NAME="school"
PASSPHRASE="betty"
KEY_BITS=4096

# Generate the RSA key pair
ssh-keygen -t rsa -b $KEY_BITS -f $KEY_NAME -N $PASSPHRASE

# Notify the user
echo "RSA key pair created:"
echo "Private key: $KEY_NAME"
echo "Public key: $KEY_NAME.pub"
#!/bin/bash

# Set the parameters
KEY_NAME="school"
PASSPHRASE="betty"
KEY_BITS=4096

# Generate the RSA key pair
ssh-keygen -t rsa -b $KEY_BITS -f $KEY_NAME -N $PASSPHRASE

# Notify the user
echo "RSA key pair created:"
echo "Private key: $KEY_NAME"
echo "Public key: $KEY_NAME.pub"
